### ISSUE TITLE
roadmap for building an API

### ISSUE THREAD

**Issue by shayaan245** [shayaan245/api#1]
STEP - 1 : Building an API 
- [ ] This test is about to create a simple API that will work with Users, Clients and Companies.

STEP -2 : Entities
- [ ] create these 3 entities
  - [ ] Users
  - [ ] companies
  - [ ] clients

STEP -2.1 Creating new entities like follows
2.1.1 Client entity

- [ ] Every Client need these fields
 - [ ] name
 - [ ] User (relational User field)
 - [ ] email (only valid emails accepted)
 - [ ] phone (only numbers accepted)

2.1.2 CLIENTUSER ENTITY

- [ ] You need to create this relational entity from scratch. This will relate client with users and contains more properties.
 - [ ]  client
 - [ ]  users
 - [ ]  createdAt
 - [ ] updatedAt
 - [ ] deletedAt
 - [ ] active

2.1.3 COMPANY ENTITY
- [ ] You need to add this fields to the actual entity
 - [ ] A related Company
 - [ ]  An inverse side relationship named users for retrieving all the Users for the company.

2.2 : CREATE THE FOLLOWING ENDPOINTS FOR
2.2.1  List app Users
- [ ] The endpoint needs to be able to filter by username.

2.2.2 - Replace some User fields at once
- [ ] The endpoint must update all fields at once.

2.2.3 - Create some Client
- [ ] Needs to validate that the company used isn't taken by other Client yet.

2.2.4 - Change any Client field
- [ ] The endpoint should be able to change any single field at a time, many, or even all at once.

STEP - 3 SQL

3.1 Create some function with some custom query for the following

3.1.1 Search for Companies by employees range.
- [ ]  Employees range: i.e. list Companies that has employees range between 500 and 2000

3.1.2  Search for Clients by:
- [ ] User: i.e. retrieve all Clients a User belongs to
- [ ] Name: i.e. search within the company's name text

3.1.3 Using one raw SQL:
- [ ] get a list of companies where each company has max revenue in its industry: e.g. Amazon for E-commerce

STEP - 4 SECURITY
- [ ] Secure the Create Client endpoint (2.3) to allow only ROLE_ADMIN users to use it

STEP - 5 REGEX
5.1 Add some regex
- [ ] add some regex to validate emails on GET /user/profile endpoint.

STEP - 6 UNIT AND/OR FUNCTIONAL TESTS

6.1 Assert tests from the list below
- [ ] There is only 1 company with more than 200000 employees.
- [ ] A ROLE_USER user can NOT create a User
- [ ] A Client can be created properly
- [ ] Assert that result from (3.3) contains Amazon and Google and not contains any other company from E-Commerce industry
